### PR TITLE
Design changes

### PR DESCRIPTION
**Pull request by saraNoigershel**

### CODE REVIEW

**Review by sara-lea351 — APPROVED** [review]
technical approvel

**Comment by saraNoigershel** [comment]
hi, There are classes and function signatures for events, db proxies and db proxy endpoints. can you approve @riki7649255

**Review by riki7649255 — CHANGES_REQUESTED** [review]
1. in DBProxyController- why all functions are for single proxy, and then- describe_db_proxies?
2. rename enent_identifier => event_identifier

everything but that looks great, well done!
please change and send me to approve

**Comment by saraNoigershel** [comment]
in DBProxyController- why all functions are for single proxy, and then- describe_db_proxies?
This was the function in rds
should I change it?
rename enent_identifier => event_identifier
Is it not the same?

**Review by riki7649255 — APPROVED** [review]

**Pull request merged**
