### PR TITLE
add bucket- class & model

### PR DESCRIPTION
**Pull request by rachel-8511**

### CODE REVIEW

**Review by sara-lea351 — APPROVED** [review]
technical approval

**Comment by ShaniStrassProg** [comment]
technical approval

**Comment by ShaniStrassProg** [comment]
technical approval

**Review by ShaniStrassProg — COMMENTED** [review]
techtical

**Review by ShaniStrassProg — APPROVED** [review]

**Review by riki7649255 — COMMENTED** [review]
why controller is missing?

**Pull request merged**
