### PR TITLE
Implement 5 functions

### PR DESCRIPTION
**Pull request by Malki1844**
I implemented 5 s3 functions on my file system.
I would appreciate it if you would give me an opinion,
thank you and have a good day!

@riki7649255

### CODE REVIEW

**Review by Mychaly — APPROVED** [review]
TECHNICL APPROVAL

**Review by shana9317 — COMMENTED** [review]
TECHNICL APPROVAL

**Review by shana9317 — APPROVED** [review]
TECHNICL APPROVAL

**Review by Mychaly — APPROVED** [review]
TECHNICAL APPROVAL

**Review by riki7649255 — COMMENTED** [review]
Hi Malki, good work, looking great!
please change the following:
- for obj_key, obj_metadata in bucket_metadata.get("objects", {}).items(): =>
for key, metadata in bucket.objects.get_metadata()
and write get functions
- suggest another syntax for that:  "ObjectLockEnabled": object_lock["objectLockEnabled"] if object_lock else "DISABLED"
- change boolean parameters to be named {}_flag, fir example is_sync => sync_flag. parameters that not comply with this instruction- if exist so in aws API its ok. otherwise- change.
- remove unnecessary print() from code (probably leftovers from development / debugging)
- use single qoute to surrond strings (and not double)

that's not all, but its a good point to start.
good luck!

**Pull request merged**
