### PR TITLE
DBCluster implementation

### PR DESCRIPTION
**Pull request by sara-lea351**

### CODE REVIEW

**Review by riki7649255 — CHANGES_REQUESTED** [review]
DB/NEW_KT_DB/Controller/DBClusterController.py
1. remove the main block and save it locally, you will use it for integration

DB/NEW_KT_DB/DataAccess/DBClusterManager.py
2. move object_name, pk_column, table_schema to the init() method of the model as static attributes. ( I see you already have it inside the model now, so just remove it from the manager and use the attributes of the model)

DB/NEW_KT_DB/Service/Classes/DBClusterService.py
3. I think it's better to put all related validations inside one internal function with intuitive name, for example: _validate_sent_parameters(**kwargs) and from there to call all the validations

DB/NEW_KT_DB/Test/DBClusterTests.py
4. you used multiple times the dictionary variable cluster_data. put it inside the init() method of the test class and if you need sometimes different values for some key you can create internal function for it. do the same for other usefull variables.
5. line 204: remove empty lines

**Review by riki7649255 — CHANGES_REQUESTED** [review]
almost perfect:

1. DB/NEW_KT_DB/Service/Classes/DBClusterService.py- use and throw custom execption, that will be your answer to : why did you use **kwargs for init() model method? to learn and use validations... so please create custome exception for that and not just "Error"

DB/NEW_KT_DB/Test/DBClusterTests.py- 
2. I think the function db_cluster_valid_parameters() is not needed, if you dont enabled modifying values of this dictionary, I would use static value- only dictionary assignment and not function

**Review by riki7649255 — CHANGES_REQUESTED** [review]
1. please go over all pushed files and remove commented code, empty lines and all other development leftovers if exist

DB/NEW_KT_DB/Test/DBClusterTests.py-
2. move cluster_data dictionary outside the functions as static parameter and use it from inside the functions

**Review by riki7649255 — CHANGES_REQUESTED** [review]
DB/NEW_KT_DB/Test/DBClusterTests.py
1. remove commented code
2. move cluster_data dict to top of the file, right after the imports. maybe upper case? up to you

**Review by riki7649255 — APPROVED** [review]

**Review by rachel-8511 — APPROVED** [review]

**Review by ShaniStrassProg — APPROVED** [review]

**Pull request merged**
