### PR TITLE
Dbmng 107 naive implementation of aws rds api's functions

### PR DESCRIPTION
**Pull request by saraNoigershel**
6 functions of rds, in topics: db instances and db snapshots

### CODE REVIEW

**Comment by saraNoigershel** [comment]
hi, this is my functions to merge
@riki7649255

**Review by Efrat1710 — APPROVED** [review]
Technical Approval

**Review by riki7649255 — COMMENTED** [review]
Hi Sara, your code looks great! here are some small problems:
1.     select_query = f'''SELECT * FROM object_management WHERE class_name = ? and object_id = ?'''
    select_params = (class_name, object_id)
=>
    select_query = f'''SELECT * FROM object_management WHERE class_name = {class_name} and object_id = {object_id}'''
2. please use allways """ for documentation, and simgle qoute to surround strings (and not double)
3. check_if_exists_in_table- mybe wrong syntax? I dont get the name meaning
4. why did you use execute_query () and cursor.execute() both? whats the difference?
5. want_all flag- change all boolean parameters to be named {}_flag as the menaing, for example sync_flag, del_flag, etc. and make it intuitive I dont understand want_all at all...
6. maybe create function commit_and_close() that will do these 2 usefull actions: conn.commit(), conn.close()

thats it for now, I will look deeper next week after infrastructure implementation & compliance.
good luck!

**Review by saraNoigershel — COMMENTED** [review]
Hi, I made the necessary changes. Here are a few notes:

1.I could change the syntax of the queries (so that the parameters are within the queries) only if I changed the quotes surrounding the query from ''' to " so that I could wrap a string variable with '. Otherwise, it causes issues.
Example: f"SELECT * FROM {table} WHERE object_id = '{object_id}'" and not f"SELECT * FROM {table} WHERE object_id = {object_id}".

2.I changed the function name from check_if_exists_in_table(db, table, object_id) to check_if_object_exists_in_table(db, table, object_id).
I hope this is more understandable.

3.I only run cursor.execute() once in the program, which is in the execute_query function.
This is a function I built so that I don’t have to open and close a connection in every function that interacts with the database.
This function receives a query and takes care of executing it. In all other parts of the code, I directed the query to this function.

4.Because of this, I also perform the commit and close only in the execute_query function, so there is no need to create a separate function for that.
In fact, I’m not entirely sure it’s correct to open a connection, commit changes, and close it for each query.
When I have a set of operations, it might be better to do them all within the same connection.
For now, most of my functions are small, so this worked out fine.

**Pull request closed without merging**
