### PR TITLE
Trying division into layers sarit yehudit

### PR DESCRIPTION
**Pull request by sarit-r**

### CODE REVIEW

**Review by riki7649255 — CHANGES_REQUESTED** [review]
1. rename all your DBInstance references to DBSInstance, we push only working code- and if you import DBInstance and there are 2 - you will get a failure

DB/NEW_KT_DB/Controller/SDBInstanceController.py
2. why do you need def close_connections(self): ?

DB/NEW_KT_DB/DataAccess/ObjectManager.py
3. discard changes
4. line 14- please add documentation, do it for all this file and for all other files
5. line 46- remove commented code and all other development leftovers if exist

DB/NEW_KT_DB/Exceptions/DBInstanceExceptions.py
6. I think you should throw intuitive error message from the classes and not use pass.

DB/NEW_KT_DB/Service/Classes/SDBInstanceService.py
7. the only place to touch DB is DBManager. you have here some functions that already exists in there, some not- so you can move it to there. buy you should not have in this file connection to DB.

DB/NEW_KT_DB/Test/conftest.py
8. what is ths file? and the name?

DB/NEW_KT_DB/Test/test_db_instance_controller.py
9. please rename file to camel case and align with project naming conventions => DBInstanceTest, do it for DB/NEW_KT_DB/Test/test_db_snapshot_controller.py too.

DB/NEW_KT_DB/Test/test_sql_commands.py
10. I guess it could become our DBManager test file? would you like to adjust?

DB/NEW_KT_DB/Test__init__.py
11. what this file used for?

run_test.py
12. discard changes, you can save it locally for yourself and use it for integration.

test_db.sqlite
13. ignore this fie we already have db file in the project

**Comment by sarit-r** [comment]
1. I think I changed the imports in all places - the tests pass...
2. You are right, we did it for a specific test - we deleted it.
3. The changes have been cancelled.
4. What file do you mean? In general, I added documentation...
5. As above.
6. Corrected.
7. I think you don't understand why I use it.
   - The `SQLCommandHelper` in the `SDBInstanceService` file is used to support SQL operations on the DBs inside the `db_instance`! It's not for saving in the management tables.
   - Because of the way we chose to implement the `db_instance`, it does not support normal SQLite operations, so we created our own shell to support these operations.
   - Of course, we need to expand the `SQLCommandHelper`, but these are the basic operations.
8. The file `conftest.py` is a special pytest configuration file. It defines shared fixtures for testing, including setup for database controllers and services. This file allows for consistent test environments across multiple test files in the project.
9. Corrected.
10. As I explained in section 7, there is no connection between the SQL commands and the `DBManager`.
11. Doesn't belong to us, deleted.
12. Not sure I understood what you mean; I deleted the file.
13. Corrected.

**Review by riki7649255 — CHANGES_REQUESTED** [review]
DB/NEW_KT_DB/DataAccess/ObjectManager.py
1. discard changes

DB/NEW_KT_DB/DataAccess/SDBInstanceManager.py
2. you have 2 different conventions for function names- camel case and snake. I think in python we would prefer the snake case. please change.

DB/NEW_KT_DB/Service/Classes/SDBInstanceService.py
3. create SQLManager for DB != sqlite operations 

DB/NEW_KT_DB/Test/conftest.py
4. what this file is used for? and the name?

test_mng_table.sqlite

5. ignore this fie we already have db file in the project

**Comment by sarit-r** [comment]
**1.** I didn't make any changes, I copied the current version in main.

**2.** What do you mean? I don't see 2 versions, maybe you mean Yael Karo's files?

**4.** I answered in section 8 above... - The file `conftest.py` is a special pytest configuration file. It defines shared fixtures for testing, including setup for database controllers and services. This file allows for consistent test environments across multiple test files in the project.

**5.** I deleted it.

**Comment by yehuditSHSHSH** [comment]
about numbe 2, In all the files, including your example file, they were all done in the form of camel case - we did it that way too, except for one function that we changed now.

**Pull request closed without merging**
