### PR TITLE
filter object added

### PR DESCRIPTION
**Pull request by Tem-M**
a helper object for data requests

### CODE REVIEW

**Review by riki7649255 — COMMENTED** [review]
filter object does not need model, controller & service files?

**Comment by Tem-M** [comment]
> filter object does not need model, controller & service files?

As far as I can tell it doesn't, it's not an object that can be customized, there is a fixed set of filters that users can apply to requests and that's it. We don't have to keep live objects, and they can really just be represented as Json objects.

**Review by riki7649255 — APPROVED** [review]
Ill approve it even thought Im not sure this is make sense. we will discuss it later if needed.

**Comment by Tem-M** [comment]
> Ill approve it even thought Im not sure this is make sense. we will discuss it later if needed.

ok

**Review by eti-youngreis — APPROVED** [review]

**Pull request merged**
